export const FETCH_CHART_DATA_REQUEST = 'FETCH_CHART_DATA_REQUEST';
export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';

export const FETCH_LIST_DATA_REQUEST = 'FETCH_LIST_DATA_REQUEST';
export const FETCH_LIST_DATA_SUCCESS = 'FETCH_LIST_DATA_SUCCESS';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_WEBSITES_REQUEST = 'FETCH_WEBSITES_REQUEST';
export const FETCH_WEBSITES_SUCCESS = 'FETCH_WEBSITES_SUCCESS';

export const FETCH_SEGMENTS_REQUEST = 'FETCH_SEGMENTS_REQUEST';
export const FETCH_SEGMENTS_SUCCESS = 'FETCH_SEGMENTS_SUCCESS';
